### ISSUE TITLE
Import Shibboleth attribute-filter.xml

### ISSUE THREAD

**Issue by Edugate** [Edugate/Jagger#35]
Feature to import a Shibboelth attribute-filter.xml would make it easy for Shibboleth IdP Admins to migrate to the GUI management offered by JAGGER

**Comment by canariecaf** [comment]
I think this would be very helpful.  It may even be improved upon if you can import the attribute-resolver.xml which would likely be needed to perform the attribute mapping FIRST and THEN import the attribute.xml

Given that the resolver.xml has credentials in it, is there a possibility of having a well crafted commandline 'sync' happen for IdP elements so that they can push relevant info into the Jagger environment?

It's almost a separate item, like an agent that someone would run and then register the agent to permit it to update the relevant Jagger record for that entity.

Chris.

**Comment by canariecaf** [comment]
Thanks for the update on it.  I realize it was a stretch goal/feature and recognize the 'wontfix' label as the way to signal it is not in the project plans.

**Comment by janul** [comment]
Hi, 
This feature is moved to Jagger2 which I just stared.
